import { readFile, writeFile } from "node:fs/promises";

import type { CommandDefinition } from "../src/runtime/registry";

const SPEC_PATH = "openapi/public.json";
const OUTPUT_PATH = "src/generated/commands.gen.ts";
const HTTP_METHODS = new Set(["get", "post", "put", "patch", "delete"]);

interface OpenApiOperation {
  operationId?: string;
  tags?: string[];
  summary?: string;
  security?: unknown[];
  parameters?: OpenApiParameter[];
  "x-platform-visibility"?: string;
}

interface OpenApiParameter {
  name?: string;
  in?: "path" | "query" | "header" | "cookie";
  required?: boolean;
}

export async function generateCommandRegistry(specPath = SPEC_PATH): Promise<string> {
  const spec = JSON.parse(await readFile(specPath, "utf8"));
  const commands = collectPublicCommands(spec);
  return renderCommandRegistry(commands);
}

export function collectPublicCommands(spec: unknown): CommandDefinition[] {
  if (!spec || typeof spec !== "object") {
    throw new Error("OpenAPI spec must be an object");
  }

  const paths = (spec as { paths?: unknown }).paths;
  if (!paths || typeof paths !== "object") {
    throw new Error("OpenAPI spec is missing paths");
  }

  const commands: CommandDefinition[] = [];
  for (const [path, methods] of Object.entries(paths as Record<string, unknown>)) {
    if (!methods || typeof methods !== "object") {
      continue;
    }
    for (const [method, rawOperation] of Object.entries(methods as Record<string, unknown>)) {
      if (!HTTP_METHODS.has(method) || !rawOperation || typeof rawOperation !== "object") {
        continue;
      }
      const operation = rawOperation as OpenApiOperation;
      if (operation["x-platform-visibility"] !== "PUBLIC") {
        continue;
      }
      if (!operation.operationId) {
        throw new Error(`Public operation at ${method.toUpperCase()} ${path} is missing operationId`);
      }
      commands.push(toCommandDefinition(method, path, operation));
    }
  }

  return commands.sort((left, right) => left.operation_id.localeCompare(right.operation_id));
}

function toCommandDefinition(method: string, path: string, operation: OpenApiOperation): CommandDefinition {
  const [resource, rawAction = method] = operation.operationId!.split(".");
  const action = kebab(rawAction);
  return {
    operation_id: operation.operationId!,
    command: `${kebab(resource)} ${action}`,
    resource: kebab(resource),
    action,
    method: method.toUpperCase(),
    path,
    tag: operation.tags?.[0] ?? kebab(resource),
    summary: operation.summary ?? operation.operationId!,
    visibility: "PUBLIC",
    requires_auth: Array.isArray(operation.security) && operation.security.length > 0,
    parameters: (operation.parameters ?? [])
      .filter((parameter) => parameter.name && parameter.in)
      .map((parameter) => ({
        name: parameter.name!,
        in: parameter.in!,
        required: parameter.required === true,
      })),
  };
}

function renderCommandRegistry(commands: readonly CommandDefinition[]): string {
  return `// Generated by scripts/generate-commands.ts. Do not edit by hand.\n` +
    `import type { CommandDefinition } from "../runtime/registry";\n\n` +
    `export const commandRegistry = ${JSON.stringify(commands, null, 2)} as const satisfies readonly CommandDefinition[];\n`;
}

function kebab(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[_\s.]+/g, "-")
    .toLowerCase();
}

if (import.meta.main) {
  try {
    const generated = await generateCommandRegistry();
    if (process.argv.includes("--check")) {
      const current = await readFile(OUTPUT_PATH, "utf8").catch(() => "");
      if (current !== generated) {
        console.error(`${OUTPUT_PATH} is out of date. Run: mise run generate`);
        process.exit(1);
      }
    } else {
      await writeFile(OUTPUT_PATH, generated);
      console.error(`Generated ${OUTPUT_PATH}`);
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
